name: Build Android APK

on:
  push:
    branches: [ main ]
    paths:
      - 'TRIAD_Mobile_app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'TRIAD_Mobile_app/**'
  release:
    types: [created]
  workflow_dispatch:  # Ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Make gradlew executable
        run: chmod +x TRIAD_Mobile_app/gradlew
      
      - name: Build Debug APK
        working-directory: TRIAD_Mobile_app
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: TRIAD_Mobile_app/app/build/outputs/apk/debug/*.apk
          retention-days: 7
      
      # Создавать Release APK только при создании релиза
      - name: Build Release APK
        if: github.event_name == 'release'
        working-directory: TRIAD_Mobile_app
        run: ./gradlew assembleRelease --stacktrace
      
      - name: Sign Release APK
        if: github.event_name == 'release'
        uses: r0adrunner/sign-android-release@v1
        with:
          releaseDirectory: TRIAD_Mobile_app/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # Это обходное решение для текущей проблемы в GitHub Actions
          BUILD_TOOLS_VERSION: "34.0.0"
      
      - name: Upload Release APK to GitHub Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.sign_app.outputs.signedReleaseFile }}
          asset_name: app-release-signed.apk
          asset_content_type: application/vnd.android.package-archive 