name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'TRIAD_Mobile_app/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'TRIAD_Mobile_app/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Make gradlew executable
        run: chmod +x TRIAD_Mobile_app/gradlew
      
      - name: Run lint
        working-directory: TRIAD_Mobile_app
        run: ./gradlew lint --stacktrace
      
      - name: Upload lint results
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: TRIAD_Mobile_app/app/build/reports/lint-results-debug.html
          retention-days: 7
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Make gradlew executable
        run: chmod +x TRIAD_Mobile_app/gradlew
      
      - name: Run tests
        working-directory: TRIAD_Mobile_app
        run: ./gradlew test --stacktrace
      
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TRIAD_Mobile_app/app/build/reports/tests/
          retention-days: 7 