name: Simple Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
      - name: Make gradlew executable
        run: chmod +x gradlew
        
      - name: Build debug APK
        run: ./gradlew assembleDebug
      
      - name: Upload APK to GitHub Artifacts using bash
        run: |
          mkdir -p apk
          cp app/build/outputs/apk/debug/app-debug.apk apk/
          echo "APK file generated at app/build/outputs/apk/debug/app-debug.apk"
          echo "::set-output name=apk_path::app/build/outputs/apk/debug/app-debug.apk" 